name = "Hugo Fresh+"
license = "MIT"
licenselink = "https://github.com/jasoncavinder/hugo-fresh-plus/blob/master/LICENSE.md"
description = "A Hugo adaptation of the Fresh theme from CSS Ninja and enhanced with newer Hugo features and with client use in mind."
homepage = "https://github.com/jasoncavinder/hugo-fresh-plus"
tags = ["responsive", "light", "company", "clean", "landing page"]
features = []
min_version = "0.110.0"

[author]
  name = "Jason Cavinder"
  homepage = "https://github.com/jasoncavinder"
